### ISSUE TITLE
Override the Client

### ISSUE THREAD

**Issue by Misosooup** [BedrockStreaming/StatsdBundle#71]
Would it be possible to override the in src/Client/Client.php. At the moment, everything is loaded through the Extension and it doesn't seem like there is a way for us to declare a custom Client. 

Would it be possible to update the following line so that it takes in a custom alias that points to a custom client in the config.
` $definition = new Definition('M6Web\Bundle\StatsdBundle\Client\Client');`
to something like
` $definition = new Definition([anAliasToACustomClient]);`

**Comment by omansour** [comment]
seems possible to me. Don't hesitate to propose a PR doing so
