### ISSUE TITLE
Symfony/PropertyAccessor constructor deprecation

### ISSUE THREAD

**Issue by simonberger** [BedrockStreaming/StatsdBundle#78]
We upgraded to symfony/property-access version 5.3 from 4.4 and get a deprecation message, coming from this bundle:

```
 User Deprecated: Since symfony/property-access 5.2: Passing a boolean as the first argument to "Symfony\Component\PropertyAccess\PropertyAccessor::__construct()" is deprecated. Pass a combination of bitwise flags instead (i.e an integer).
```

Here is the related upgrade entry (providing just the above information):

https://github.com/symfony/symfony/blob/5.4/UPGRADE-5.2.md#propertyaccess

**Comment by jdecool** [comment]
Hi @simonberger, thanks for your feedback.

This issue has been fixed in #85.
Last release https://github.com/BedrockStreaming/StatsdBundle/releases/tag/v4.1.0 fix this issue.
