### ISSUE TITLE
PHP8 compatability

### ISSUE THREAD

**Issue by bullder** [BedrockStreaming/StatsdBundle#82]
Do you have any plans to prepare this bundle for supporting php8?

**Comment by jdecool** [comment]
Our company projects using this package should be updated in the next months in PHP 8.1

So it will imply to add PHP 8 compatibility.
But PR are welcome.

**Comment by bullder** [comment]
I did pr to comply newer version of coke but looking forward for upgraded version which will be compliant with php8 
https://github.com/BedrockStreaming/StatsdBundle/pull/81
