### ISSUE TITLE
PHP 8.x

### ISSUE THREAD

**Issue by fbiesse** [BedrockStreaming/StatsdBundle#84]
Is it considered do make this bundle compatible with PHP 8.x
We currently use this bundle in production and upgrading our applications to PHP 8.1.
So at the moment we supressed the dependency because the composer.json does not allow PHP 8.1.
Do you have any planning for it ?
Thank you.

**Comment by jdecool** [comment]
Hi @fbiesse,

PHP 8 compatibility has just been release for this bundle and it's available in https://github.com/BedrockStreaming/StatsdBundle/releases/tag/v4.1.0.
